package com.karmelos.ksimulator.view.swing;

/**
 *HelpTipsPanel: pop up box with help information on how to use the application
 * 
 * @author Adebayo Adeniyan
 */
public class HelpTipsPanel extends javax.swing.JPanel {

    /**
     * Creates new form HelpTipsPanel
     */
    public HelpTipsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 25, 1, 1));

        jTextPane1.setEditable(false);
        jTextPane1.setText("\t\tWELCOME\n\n             KSimulator is a software program that provides you the \n             power to experience simulation of real life scenarios.\n\n >Start New Session\n             1. Tap or click the File menu, and then tap or click New.\n\n             2. Enter your session name, and then tap or click OK.\n\n> Save session\n             1. Tap or click the File menu, and then tap or click Save.\n\n             2. Confirm your user details, and then tap or click OK.\n\n> View 3D Image\n\n             1. Tap or click 3D View image menu.\n\n> Print Session <Include Printer Setup>\n\n             1. Tap or click the File menu, and then tap or click Print.\n"); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
