package com.karmelos.ksimulator.view.swing;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * PrinterPanel: pop up box allowing user to print assembly view(Workspace/3Dview)
 *
 * @author Adebayo Adeniyan
 */
public class PrinterPanel extends javax.swing.JPanel {

    /**
     * Creates new form PrinterPanel
     */
    public PrinterPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        printBtn = new javax.swing.JButton();
        printWorkspace = new javax.swing.JCheckBox();
        print3D = new javax.swing.JCheckBox();
        errorlabel = new javax.swing.JLabel();
        printIcon = new javax.swing.JLabel();

        printBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        printBtn.setText("Print");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });

        printWorkspace.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        printWorkspace.setText("Print Workspace");
        printWorkspace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printWorkspaceMouseClicked(evt);
            }
        });

        print3D.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        print3D.setText("Print 3D View");
        print3D.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                print3DMouseClicked(evt);
            }
        });
        print3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print3DActionPerformed(evt);
            }
        });

        errorlabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        errorlabel.setForeground(new java.awt.Color(255, 0, 0));

        printIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/karmelos/ksimulator/2ndbaricon/print.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(printIcon)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(printWorkspace)
                            .addComponent(print3D)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(errorlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(printBtn)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(printIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(printWorkspace)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(print3D)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(printBtn)
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void print3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print3DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_print3DActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        // handles user action for printing the WorkSpace View or the 3Dview or both
        
         if(!printWorkspace.isSelected()&&!print3D.isSelected())//conditional statement when no Print mode is selected
        {
            printBtn.setEnabled(false);//print button is disabled
        errorlabel.setText("a print mode must be selected");//error text to indicate no print mode was selected
        }
         //print 
         else{ 
            SimView sm;
             try {
                 sm = new SimView(); //invokes the sim view to access the print() method
                 sm.print();//prints
             } catch (IOException ex) {
                 Logger.getLogger(PrinterPanel.class.getName()).log(Level.SEVERE, null, ex);
             }
            
        }
    }//GEN-LAST:event_printBtnActionPerformed

    private void printWorkspaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printWorkspaceMouseClicked
      // enables print button and clear error message
       printBtn.setEnabled(true);
       errorlabel.setText(null);
    }//GEN-LAST:event_printWorkspaceMouseClicked

    private void print3DMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print3DMouseClicked
        // enable print button and clear error message
     printBtn.setEnabled(true);
     errorlabel.setText(null);
    }//GEN-LAST:event_print3DMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorlabel;
    private javax.swing.JCheckBox print3D;
    private javax.swing.JButton printBtn;
    private javax.swing.JLabel printIcon;
    private javax.swing.JCheckBox printWorkspace;
    // End of variables declaration//GEN-END:variables
}
